# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

# Config reference:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

---
version: 2
multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
  - package-ecosystem: "maven"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
    ignore:
      # Ignore major version updates to spring-boot-starter-parent
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.cloud:spring-cloud-dependencies"
        update-types: ["version-update:semver-major"]
