# we can configure everything here, except
# - copyright garbage
# - evaluator rules
# - fix text provider
# - classifications
# - reporter templates

# - [ ] Configure ScanCode to ignore files like CONTRIBUTING.md
# - [ ] Differentiate between AGPL as "copyleft-network" and GPL as "copyleft"?
#
#Stuff to exclude on ScanCode level
#- CONTRIBUTING.md
#- CONTRIBUTING.adoc
#- README.md
#- README.adoc
#- README*.html
#- readme*.html
#- NOTICE.txt
#- NOTICE.md

package_configurations:

### GENERIC

- id: "Maven:org.springframework:spring-test:5.+"
  path_excludes:
  - pattern: "src/docs/dist/license.txt"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation of licenses of subcomponents"

- id: "Maven:org.springframework:spring-web:5.+"
  path_excludes:
  - pattern: "src/docs/dist/license.txt"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation of licenses of subcomponents"

- id: "Maven:org.springframework:spring-jcl:5.+"
  path_excludes:
  - pattern: "src/docs/dist/license.txt"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation of licenses of subcomponents"

- id: "Maven:org.aspectj:aspectjrt:1.+"
  license_finding_curations:
  - path: "ajde/src/main/java/org/aspectj/ajde/ui/swing/OptionsFrame.java"
    detected_license: "NOASSERTION"
    concluded_license: "EPL-2.0"
    reason: "INCORRECT"
    comment: "Did not recognize license"
  - path: "build/src/main/java/org/aspectj/internal/tools/build/SampleGatherer.java"
    detected_license: "NOASSERTION"
    concluded_license: "EPL-2.0"
    reason: "INCORRECT"
    comment: "Did not recognize license"

- id: "Maven:org.springframework.boot:spring-boot-autoconfigure:2.+"
  path_excludes:
  - pattern: "spring-boot-project/spring-boot-cli/src/main/content/legal/open_source_licenses.txt"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation of licenses of subcomponents"
  license_finding_curations:
  - path: "buildSrc/src/main/java/org/springframework/boot/build/classpath/CheckClasspathForConflicts.java"
    detected_license: "NOASSERTION"
    concluded_license: "Apache-2.0"
    reason: "INCORRECT"
    comment: "Did not recognize license"

- id: "Maven:org.springframework.boot:spring-boot:2.+"
  path_excludes:
  - pattern: "spring-boot-project/spring-boot-cli/src/main/content/legal/open_source_licenses.txt"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation of licenses of subcomponents"
  license_finding_curations:
  - path: "buildSrc/src/main/java/org/springframework/boot/build/classpath/CheckClasspathForConflicts.java"
    detected_license: "NOASSERTION"
    concluded_license: "Apache-2.0"
    reason: "INCORRECT"
    comment: "Did not recognize license"

- id: "Maven:io.netty:netty-resolver:4.+"
  license_finding_curations:
  - path: "**/pom.xml"
    detected_license: "NOASSERTION"
    concluded_license: "Apache-2.0"
    reason: "INCORRECT"
    comment: "Did not recognize license"

- id: "Maven:com.google.errorprone:error_prone_annotations:2.+"
  license_finding_curations:
  - path: "**/pom.xml"
    detected_license: "NOASSERTION"
    concluded_license: "Apache-2.0"
    reason: "INCORRECT"
    comment: "Did not recognize license"

- id: "Maven:org.junit.platform:junit-platform-suite-commons:1.+"
  path_excludes:
  - pattern: "LICENSE-notice.md"
    reason: "DOCUMENTATION_OF"
    comment: "License Notice"

- id: "Maven:com.jayway.jsonpath:json-path:2.+"
  license_finding_curations:
  - path: "json-path-web-test/src/main/resources/webapp/js/jsonpath-0.8.0.js"
    detected_license: "LicenseRef-scancode-polyform-free-trial-1.0.0"
    concluded_license: "MIT"
    reason: "INCORRECT"
    comment: "Recognized incorrect license"


### REPO SPECIFIC

- id: "Maven:org.testcontainers:junit-jupiter:1.+"
  license_finding_curations:
  - path: "core/src/main/java/org/testcontainers/utility/LicenseAcceptance.java"
    detected_license: "NOASSERTION"
    concluded_license: "MIT"
    reason: "NOT_DETECTED"
    comment: "License missing but package declares MIT in license file"
  path_excludes:
  - pattern: "modules/neo4j/**"
    reason: "OTHER"
    comment: "Module is not used"
  - pattern: "modules/elasticsearch/**"
    reason: "OTHER"
    comment: "Module is not used"

curations:
  packages:
  - id: "Maven:com.github.java-json-tools:json-patch:1.+"
    curations:
      comment: "Package does not declare licenses in source files. Declares dual license in LICENSE file."
      concluded_license: "LGPL-3.0-or-later AND Apache-2.0"
  - id: "Maven:com.github.java-json-tools:json-patch:1.+"
    curations:
      comment: "Package declares dual license in LICENSE and most/all source files."
      concluded_license: "LGPL-3.0-or-later AND Apache-2.0"
