package_configurations:
- id: "Maven:org.testcontainers:junit-jupiter:1.+"
  license_finding_curations:
  - path: "core/src/main/java/org/testcontainers/utility/LicenseAcceptance.java"
    detected_license: "NOASSERTION"
    concluded_license: "MIT"
    reason: "NOT_DETECTED"
    comment: "License missing but package declares MIT in license file"
  path_excludes:
  - pattern: "modules/neo4j/**"
    reason: "OTHER"
    comment: "Module is not used"
  - pattern: "modules/elasticsearch/**"
    reason: "OTHER"
    comment: "Module is not used"
