# SPDX-FileCopyrightText: 2025 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: REUSE

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-reuse:
    name: Check REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5
